resources:
  - name: jdk21-image-repo
    type: git
    source:
      uri: https://github.com/demo151996/jdk21-image-repo.git
      branch: main
  - name: jdk21-image
    type: docker-image
    source:
      repository: ghcr.io/demo151996/jdk21-image
      username: ((local-git-username))
      password: ((local-git-token))
      tag: latest
jobs:
  - name: build-jdk21-image
    plan:
      - get: jdk21-image-repo
        trigger: true
      - put: jdk21-image
        params:
          build: jdk21-image-repo
  - name: run-tasks-with-image
    plan:
      - get: jdk21-image-repo
        passed: [build-jdk21-image]
      - get: jdk21-image
        passed: [build-jdk21-image]
      - task: run-from-image
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/demo151996/jdk21-image
              tag: latest
              username: ((local-git-username))
              password: ((local-git-token))
          run:
            path: java
            args: ["-version"]
