resources:
  - name: jdk21-image-repo
    type: git
    source:
      uri: https://github.com/comcast-devx-pace/jdk21-image-repo.git
      branch: main

  - name: jdk21-image
    type: docker-image
    source:
      repository: ghcr.io/((ghcr_username))/((image_repo))
      username: ((ghcr_username))
      password: ((ghcr_token))
      tag: latest
jobs:
  - name: build-jdk21-image
    plan:
      - get: jdk21-image-repo
        trigger: true
      - put: jdk21-image
        params:
          build: jdk21-image-repo
  
  - name: run-task-with-image
    plan:
      - get: jdk21-image-repo
        passed: [build-jdk21-image]
      - get: jdk21-image
        passed: [build-jdk21-image]
      - task: run-from-image
        config:
          platform: linux
          image_resource:
            type: registry-image
          source:
            repository: ghcr.io/((ghcr_username))/((image_repo))
            tag: latest
            username: ((ghcr_username))
            password: ((ghcr_token))
          run:
            path: /app/do-something.sh
