resources:
  - name: jdk21-image-repo
    type: git
    source:
      uri: https://github.com/demo151996/jdk21-image-repo.git
      branch: main

  - name: jdk21-custom
    type: registry-image
    source:
      repository: ghcr.io/demo151996/jdk21-custom
      username: CarolineMarshel
      password: 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

jobs:
  - name: build-and-push-jdk21
    plan:
      - get: jdk21-image-repo
        trigger: true
      - put: jdk21-custom
        params:
          build: jdk21-image-repo
