resources:
  - name: jdk21-image-repo
    type: git
    source:
      uri: https://github.com/demo151996/jdk21-image-repo.git
      branch: main

  - name: jdk21-image
    type: registry-image
    source:
      repository: ghcr.io/demo151996/jdk21-custom
      username: CarolineMarshel
      password: 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

jobs:
  - name: build-and-push-jdk21
    plan:
      - get: jdk21-image-repo
        trigger: true
      - put: jdk21-image
        params:
          build: jdk21-image-repo
